name: Build

on:
  push:
  create:
    tags:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup node
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
      - name: Setup gradlew
        run:
          ./gradlew genEclipseRuns
      - name: Build
        run:
          ./gradlew genEclipseRuns